---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gimp
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 2
  ExtUtils::Depends: 0
  Gtk2: 1
  IO::All: 0
  PDL: 2
version: 2.300001
