---
abstract: unknown
author:
  - unknown
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gimp
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://git.gnome.org/gimp-perl
version: 2.3003
